name: Build & deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: newman run test/live_chat.postman_collection.json -e test/postman_environment.json

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}name: Build & deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: newman run test/live_chat.postman_collection.json -e test/postman_environment.json

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build  -t livechat:latest .

      - name: Tag docker image
        run: docker tag livechat:latest ${{ secrets.DOCKER_USERNAME }}/livechat:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/livechat:latest
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build  -t livechat:latest .

      - name: Tag docker image
        run: docker tag livechat:latest ${{ secrets.DOCKER_USERNAME }}/livechat:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/livechat:latest